/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthAuthorizationStatus = "approved" | "denied" | "expired" | "pending";

export type AuthOauthClientType = "confidential" | "public";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOauthResponseType = "code";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type StorageBuckettype = "ANALYTICS" | "STANDARD" | "VECTOR";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AcademicsAssignmentSubmissionsView {
  assignmentId: number | null;
  assignmentTitle: string | null;
  classId: number | null;
  className: string | null;
  dueDate: Timestamp | null;
  gradedBy: string | null;
  gradedOn: Timestamp | null;
  gradeLetter: string | null;
  gradePoint: number | null;
  id: number | null;
  remarks: string | null;
  schoolId: number | null;
  score: number | null;
  startDate: Timestamp | null;
  studentId: number | null;
  studentName: string | null;
  subjectId: number | null;
  subjectName: string | null;
  submissionDate: Timestamp | null;
  submissionStatus: string | null;
  teacherComment: string | null;
  termId: number | null;
  termName: string | null;
}

export interface AcademicsClassscheduleView {
  classId: number | null;
  className: string | null;
  endTime: string | null;
  id: number | null;
  lessonId: number | null;
  lessonStatus: string | null;
  lessonTitle: string | null;
  scheduledDate: Timestamp | null;
  schoolId: number | null;
  startTime: string | null;
  subjectName: string | null;
  teacherComment: string | null;
  teacherName: string | null;
  termId: number | null;
  termName: string | null;
  timetableId: number | null;
  timetableName: string | null;
}

export interface AcademicYears {
  /**
   * Short code/identifier for the academic year (e.g., AY2025, 2025-26)
   */
  code: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  endDate: Timestamp;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isCurrent: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  startDate: Timestamp;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface AdmissionStatuses {
  code: string;
  color: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  displayOrder: Generated<number | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  isFinal: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface Applicants {
  address: string | null;
  city: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  dateOfBirth: Timestamp;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  district: string | null;
  email: string | null;
  firstName: string;
  gender: string | null;
  guardianEmail: string | null;
  guardianName: string | null;
  guardianPhone: string | null;
  guardianRelationship: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  lastName: string;
  leavingCertificateNo: string | null;
  middleName: string | null;
  nationality: Generated<string | null>;
  phone: string | null;
  previousGrade: string | null;
  previousSchool: string | null;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ApplicationDecisions {
  applicantResponse: string | null;
  applicationId: Int8;
  createdAt: Generated<Timestamp | null>;
  decisionBy: Int8 | null;
  decisionDate: Generated<Timestamp | null>;
  decisionType: string;
  id: Generated<Int8>;
  /**
   * JSON: {grade_offered, stream_offered, academic_year, fees_category}
   */
  offerDetails: Json | null;
  offerValidUntil: Timestamp | null;
  rejectionReason: string | null;
  responseDate: Timestamp | null;
  responseNotes: string | null;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  waitlistNotes: string | null;
  waitlistPosition: number | null;
}

export interface ApplicationDocuments {
  applicationId: Int8;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  documentName: string;
  documentType: string;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  fileType: string | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  isVerified: Generated<boolean | null>;
  schoolId: Int8;
  uploadDate: Generated<Timestamp | null>;
  uploadedBy: Int8 | null;
  verificationNotes: string | null;
  verifiedAt: Timestamp | null;
  verifiedBy: Int8 | null;
}

export interface Applications {
  academicYear: string;
  admissionStatusId: Int8 | null;
  applicantId: Int8;
  applicationNo: string | null;
  applicationTypeId: Int8 | null;
  applyingForGrade: string;
  applyingForStream: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  decisionDate: Timestamp | null;
  decisionMadeAt: Timestamp | null;
  decisionNotes: string | null;
  decisionType: string | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  /**
   * Links to original enquiry if converted
   */
  enquiryId: Int8 | null;
  enrolledStudentId: Int8 | null;
  enrollmentDate: Timestamp | null;
  id: Generated<Int8>;
  intendedStartDate: Timestamp | null;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  reviewDate: Timestamp | null;
  reviewedBy: Int8 | null;
  schoolId: Int8;
  /**
   * Links to student record if enrolled
   */
  studentId: Int8 | null;
  submissionDate: Generated<Timestamp | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ApplicationTypes {
  code: string;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface AssessmentConductors {
  assessmentId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  id: Generated<Int8>;
  /**
   * Role in assessment: lead, invigilator, assistant, coordinator
   */
  role: Generated<string | null>;
  staffId: Int8;
}

export interface AssessmentResults {
  assessmentId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  gradedBy: Int8 | null;
  gradeLetter: string | null;
  gradePoint: Numeric | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  isFinal: Generated<boolean | null>;
  remarks: string | null;
  schoolId: Int8;
  score: Numeric;
  studentId: Int8;
  teacherComments: Generated<Json | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Assessments {
  academicYearId: Int8 | null;
  assessmentTypeId: Int8 | null;
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  date: Timestamp;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  maxScore: Numeric;
  schoolId: Int8;
  statusId: Int8 | null;
  subjectId: Int8;
  teacherComments: Generated<Json | null>;
  termId: Int8;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  weight: Generated<Numeric | null>;
}

export interface AssessmentTypes {
  code: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isDeleted: Generated<boolean | null>;
  label: string;
  schoolId: Int8 | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface AssetAssignments {
  assetId: Int8;
  assignedAt: Generated<Timestamp>;
  assignedBy: Int8 | null;
  assignmentType: Generated<string>;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  notes: string | null;
  unassignedAt: Timestamp | null;
  updatedAt: Generated<Timestamp | null>;
  userId: Int8;
}

export interface AssetMaintenanceLogs {
  assetId: Int8;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  details: Json | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  loggedAt: Generated<Timestamp | null>;
  logType: string;
  resolutionNotes: string | null;
  resolvedAt: Timestamp | null;
  technicianId: Int8 | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Assets {
  assetCode: string;
  assetTypeId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  location: string | null;
  name: string;
  nfcTag: string | null;
  purchaseDate: Timestamp | null;
  qrCode: string | null;
  schoolId: Int8;
  serialNumber: string | null;
  status: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  vendor: string | null;
  warrantyExpiry: Timestamp | null;
}

export interface AssetTypes {
  category: string;
  code: string;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isBiometric: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  purpose: Generated<string[] | null>;
  requiresCalibration: Generated<boolean | null>;
  schoolId: Int8;
  subcategory: string;
  updatedAt: Generated<Timestamp | null>;
  vendorRequirements: Json | null;
}

export interface Assignments {
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  dueDate: Timestamp;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  maxScore: Numeric;
  schoolId: Int8;
  startDate: Timestamp | null;
  statusId: Int8 | null;
  subjectId: Int8;
  teacherComments: Generated<Json | null>;
  teacherId: Int8;
  termId: Int8;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  /**
   * Weight factor for grade aggregation. Range: 0 to 10.0. Default: 0. 0 = practice only (no grade impact), higher values = more impact on final grade.
   */
  weight: Generated<Numeric | null>;
}

export interface AssignmentSubmissions {
  assignmentId: Int8;
  content: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  fileUrl: string | null;
  gradedBy: Int8 | null;
  gradeLetter: string | null;
  gradePoint: Numeric | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  remarks: string | null;
  schoolId: Int8;
  score: Numeric | null;
  statusId: Int8 | null;
  studentId: Int8;
  submissionDate: Generated<Timestamp | null>;
  teacherComments: Generated<Json | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface AttendancePolicies {
  absentAfterLateThreshold: Generated<number | null>;
  autoExcuseRules: Generated<Json | null>;
  consecutiveAbsenceAlert: Generated<number | null>;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  lateThresholdMinutes: Generated<number | null>;
  minSessionsPerDay: Generated<number | null>;
  moesMinAttendancePercent: Generated<Numeric | null>;
  name: string;
  schoolId: Int8;
  smsProvider: Generated<string | null>;
  truantDefinition: Generated<Json | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface AttendanceRecords {
  assetId: Int8 | null;
  biometricMatchConfidence: Numeric | null;
  biometricScanQuality: string | null;
  biometricTemplateHash: string | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  deviceCode: string | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  isVerified: Generated<boolean>;
  locationLat: Numeric | null;
  locationLng: Numeric | null;
  method: Generated<string>;
  recordedAt: Generated<Timestamp>;
  recordedBy: Int8;
  remark: string | null;
  schoolId: Int8;
  sessionId: Int8;
  signType: Generated<string | null>;
  status: Generated<string>;
  updatedAt: Generated<Timestamp | null>;
  userId: Int8;
  verifiedAt: Timestamp | null;
  verifiedBy: Int8 | null;
}

export interface AttendanceSessions {
  classId: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  date: Timestamp;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  endTime: string;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  meetingAgenda: string | null;
  meetingTitle: string | null;
  meetingType: string | null;
  roomId: Int8 | null;
  schoolId: Int8;
  sessionType: Generated<string>;
  startTime: string;
  status: Generated<string>;
  subjectId: Int8 | null;
  teacherId: Int8;
  termId: Int8 | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface AttendanceStatus {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface AttendanceSummary {
  attendancePercentage: Generated<Numeric | null>;
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  daysPresent: number;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  schoolId: Int8;
  status: Generated<string | null>;
  studentId: Int8;
  teacherComments: Generated<Json | null>;
  termId: Int8;
  totalDays: number;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Auditlogs {
  action: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  diff: Json | null;
  id: Generated<Int8>;
  ipAddress: string | null;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  newValue: Json | null;
  oldValue: Json | null;
  permissionResource: string | null;
  resourceId: Int8 | null;
  resourceType: string;
  roleId: Int8 | null;
  schoolId: Int8 | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  userAgent: string | null;
  userId: Int8 | null;
}

export interface AuditlogsReport {
  action: string | null;
  createdAt: Timestamp | null;
  createdBy: Int8 | null;
  id: Int8 | null;
  newValue: Json | null;
  oldValue: Json | null;
  resourceId: Int8 | null;
  resourceType: string | null;
  schoolScope: string | null;
  userId: Int8 | null;
}

export interface AuditrouteReport {
  action: string | null;
  auditId: Int8 | null;
  createdAt: Timestamp | null;
  diff: Json | null;
  method: string | null;
  permissionResource: string | null;
  resourceId: Int8 | null;
  resourceType: string | null;
  roleId: Int8 | null;
  route: string | null;
  schoolId: Int8 | null;
  userId: Int8 | null;
}

export interface AuthAuditLogEntries {
  createdAt: Timestamp | null;
  id: string;
  instanceId: string | null;
  ipAddress: Generated<string>;
  payload: Json | null;
}

export interface AuthCustomOauthProviders {
  acceptableClientIds: Generated<string[]>;
  attributeMapping: Generated<Json>;
  authorizationParams: Generated<Json>;
  authorizationUrl: string | null;
  cachedDiscovery: Json | null;
  clientId: string;
  clientSecret: string;
  createdAt: Generated<Timestamp>;
  discoveryCachedAt: Timestamp | null;
  discoveryUrl: string | null;
  emailOptional: Generated<boolean>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  identifier: string;
  issuer: string | null;
  jwksUri: string | null;
  name: string;
  pkceEnabled: Generated<boolean>;
  providerType: string;
  scopes: Generated<string[]>;
  skipNonceCheck: Generated<boolean>;
  tokenUrl: string | null;
  updatedAt: Generated<Timestamp>;
  userinfoUrl: string | null;
}

export interface AuthFlowState {
  authCode: string | null;
  authCodeIssuedAt: Timestamp | null;
  authenticationMethod: string;
  codeChallenge: string | null;
  codeChallengeMethod: AuthCodeChallengeMethod | null;
  createdAt: Timestamp | null;
  emailOptional: Generated<boolean>;
  id: string;
  inviteToken: string | null;
  linkingTargetId: string | null;
  oauthClientStateId: string | null;
  providerAccessToken: string | null;
  providerRefreshToken: string | null;
  providerType: string;
  referrer: string | null;
  updatedAt: Timestamp | null;
  userId: string | null;
}

export interface AuthIdentities {
  createdAt: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identityData: Json;
  lastSignInAt: Timestamp | null;
  provider: string;
  providerId: string;
  updatedAt: Timestamp | null;
  userId: string;
}

export interface AuthInstances {
  createdAt: Timestamp | null;
  id: string;
  rawBaseConfig: string | null;
  updatedAt: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authenticationMethod: string;
  createdAt: Timestamp;
  id: string;
  sessionId: string;
  updatedAt: Timestamp;
}

export interface AuthMfaChallenges {
  createdAt: Timestamp;
  factorId: string;
  id: string;
  ipAddress: string;
  otpCode: string | null;
  verifiedAt: Timestamp | null;
  webAuthnSessionData: Json | null;
}

export interface AuthMfaFactors {
  createdAt: Timestamp;
  factorType: AuthFactorType;
  friendlyName: string | null;
  id: string;
  lastChallengedAt: Timestamp | null;
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  lastWebauthnChallengeData: Json | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updatedAt: Timestamp;
  userId: string;
  webAuthnAaguid: string | null;
  webAuthnCredential: Json | null;
}

export interface AuthOauthAuthorizations {
  approvedAt: Timestamp | null;
  authorizationCode: string | null;
  authorizationId: string;
  clientId: string;
  codeChallenge: string | null;
  codeChallengeMethod: AuthCodeChallengeMethod | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Generated<Timestamp>;
  id: string;
  nonce: string | null;
  redirectUri: string;
  resource: string | null;
  responseType: Generated<AuthOauthResponseType>;
  scope: string;
  state: string | null;
  status: Generated<AuthOauthAuthorizationStatus>;
  userId: string | null;
}

export interface AuthOauthClients {
  clientName: string | null;
  clientSecretHash: string | null;
  clientType: Generated<AuthOauthClientType>;
  clientUri: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  grantTypes: string;
  id: string;
  logoUri: string | null;
  redirectUris: string;
  registrationType: AuthOauthRegistrationType;
  tokenEndpointAuthMethod: string;
  updatedAt: Generated<Timestamp>;
}

export interface AuthOauthClientStates {
  codeVerifier: string | null;
  createdAt: Timestamp;
  id: string;
  providerType: string;
}

export interface AuthOauthConsents {
  clientId: string;
  grantedAt: Generated<Timestamp>;
  id: string;
  revokedAt: Timestamp | null;
  scopes: string;
  userId: string;
}

export interface AuthOneTimeTokens {
  createdAt: Generated<Timestamp>;
  id: string;
  relatesTo: string;
  tokenHash: string;
  tokenType: AuthOneTimeTokenType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AuthRefreshTokens {
  createdAt: Timestamp | null;
  id: Generated<Int8>;
  instanceId: string | null;
  parent: string | null;
  revoked: boolean | null;
  sessionId: string | null;
  token: string | null;
  updatedAt: Timestamp | null;
  userId: string | null;
}

export interface AuthSamlProviders {
  attributeMapping: Json | null;
  createdAt: Timestamp | null;
  entityId: string;
  id: string;
  metadataUrl: string | null;
  metadataXml: string;
  nameIdFormat: string | null;
  ssoProviderId: string;
  updatedAt: Timestamp | null;
}

export interface AuthSamlRelayStates {
  createdAt: Timestamp | null;
  flowStateId: string | null;
  forEmail: string | null;
  id: string;
  redirectTo: string | null;
  requestId: string;
  ssoProviderId: string;
  updatedAt: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  createdAt: Timestamp | null;
  factorId: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  notAfter: Timestamp | null;
  oauthClientId: string | null;
  refreshedAt: Timestamp | null;
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refreshTokenCounter: Int8 | null;
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refreshTokenHmacKey: string | null;
  scopes: string | null;
  tag: string | null;
  updatedAt: Timestamp | null;
  userAgent: string | null;
  userId: string;
}

export interface AuthSsoDomains {
  createdAt: Timestamp | null;
  domain: string;
  id: string;
  ssoProviderId: string;
  updatedAt: Timestamp | null;
}

export interface AuthSsoProviders {
  createdAt: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resourceId: string | null;
  updatedAt: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  bannedUntil: Timestamp | null;
  confirmationSentAt: Timestamp | null;
  confirmationToken: string | null;
  confirmedAt: Generated<Timestamp | null>;
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  email: string | null;
  emailChange: string | null;
  emailChangeConfirmStatus: Generated<number | null>;
  emailChangeSentAt: Timestamp | null;
  emailChangeTokenCurrent: Generated<string | null>;
  emailChangeTokenNew: string | null;
  emailConfirmedAt: Timestamp | null;
  encryptedPassword: string | null;
  id: string;
  instanceId: string | null;
  invitedAt: Timestamp | null;
  isAnonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  isSsoUser: Generated<boolean>;
  isSuperAdmin: boolean | null;
  lastSignInAt: Timestamp | null;
  phone: Generated<string | null>;
  phoneChange: Generated<string | null>;
  phoneChangeSentAt: Timestamp | null;
  phoneChangeToken: Generated<string | null>;
  phoneConfirmedAt: Timestamp | null;
  rawAppMetaData: Json | null;
  rawUserMetaData: Json | null;
  reauthenticationSentAt: Timestamp | null;
  reauthenticationToken: Generated<string | null>;
  recoverySentAt: Timestamp | null;
  recoveryToken: string | null;
  role: string | null;
  updatedAt: Timestamp | null;
}

export interface AuthWebauthnChallenges {
  challengeType: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  sessionData: Json;
  userId: string | null;
}

export interface AuthWebauthnCredentials {
  aaguid: string | null;
  attestationType: Generated<string>;
  backedUp: Generated<boolean>;
  backupEligible: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  credentialId: Buffer;
  friendlyName: Generated<string>;
  id: Generated<string>;
  lastUsedAt: Timestamp | null;
  publicKey: Buffer;
  signCount: Generated<Int8>;
  transports: Generated<Json>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface CampusAccessLogs {
  assetId: Int8 | null;
  biometricMatchConfidence: Numeric | null;
  biometricScanQuality: string | null;
  biometricTemplateHash: string | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  deviceCode: string | null;
  eventAt: Generated<Timestamp>;
  eventType: string;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  isVerified: Generated<boolean | null>;
  locationLat: Numeric | null;
  locationLng: Numeric | null;
  locationName: string | null;
  method: Generated<string>;
  recordedAt: Generated<Timestamp>;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  userId: Int8;
  verifiedAt: Timestamp | null;
  verifiedBy: Int8 | null;
}

export interface ClassAttendance {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  lessonId: Int8;
  remark: string | null;
  schoolId: Int8;
  status: string;
  studentId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Classes {
  academicYear: string;
  capacity: number | null;
  classTeacherId: Int8 | null;
  code: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  curriculumId: Int8 | null;
  description: string | null;
  gradeLevelId: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  room: string | null;
  schoolId: Int8;
  stream: string | null;
  streamId: Int8 | null;
  teacherId: Int8 | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ClassStudents {
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  enrollmentDate: Generated<Timestamp | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  schoolId: Int8;
  studentId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ClassTeachers {
  academicYear: string | null;
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  isPrimary: Generated<boolean | null>;
  schoolId: Int8;
  subjectId: Int8 | null;
  teacherId: Int8;
  termId: Int8 | null;
}

export interface ContactTypes {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Countries {
  continent: string | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  isoCode: string;
  name: string;
  phoneCode: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Curricula {
  code: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Departments {
  code: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface DisciplinaryIncidents {
  actionTaken: string | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string;
  id: Generated<Int8>;
  incidentDate: Timestamp | null;
  incidentStatus: Generated<string | null>;
  incidentType: string | null;
  isDeleted: Generated<boolean | null>;
  location: string | null;
  reportedBy: Int8 | null;
  resolutionNotes: string | null;
  resolvedAt: Timestamp | null;
  resolvedBy: Int8 | null;
  schoolId: Int8;
  severity: string | null;
  staffId: Int8;
  updatedAt: Generated<Timestamp | null>;
  witnesses: string | null;
}

export interface Districts {
  code: string | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface DocumentTypes {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface EducationLevels {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface EmploymentTypes {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface EnquirerCategories {
  code: string;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  displayOrder: Generated<number | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  /**
   * TRUE if enquirer must be logged in (existing users)
   */
  requiresUserId: Generated<boolean | null>;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface Enquiries {
  academicYear: string | null;
  assignedAt: Timestamp | null;
  assignedBy: Int8 | null;
  assignedTo: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string;
  enquirerAddress: string | null;
  enquirerCategoryId: Int8 | null;
  enquirerCity: string | null;
  enquirerEmail: string | null;
  enquirerName: string;
  enquirerPhone: string | null;
  enquirerPostalCode: string | null;
  enquirerState: string | null;
  enquiryCategoryId: Int8 | null;
  enquiryDate: Generated<Timestamp | null>;
  enquirySourceId: Int8 | null;
  followUpDate: Timestamp | null;
  followUpNotes: string | null;
  id: Generated<Int8>;
  interestedGrade: string | null;
  interestedStream: string | null;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  lastContactDate: Timestamp | null;
  nextAction: string | null;
  priority: Generated<string | null>;
  referenceNo: string | null;
  rejectionReason: string | null;
  resolutionNotes: string | null;
  resolvedBy: Int8 | null;
  resolvedDate: Timestamp | null;
  schoolId: Int8;
  staffId: Int8 | null;
  status: Generated<string | null>;
  studentId: Int8 | null;
  subject: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  /**
   * Links to existing user if enquirer is registered (parent, student, staff)
   */
  userId: Int8 | null;
}

export interface EnquiryCategories {
  code: string;
  color: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  displayOrder: Generated<number | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  parentId: Int8 | null;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface EnquiryNotes {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  enquiryId: Int8;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  isPrivate: Generated<boolean | null>;
  note: string;
  noteType: Generated<string | null>;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface EnquirySources {
  code: string;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface Enrollments {
  academicYear: string;
  applicationId: Int8;
  completedAt: Timestamp | null;
  completedBy: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  /**
   * Array of submitted document names
   */
  documentsSubmitted: Generated<Json | null>;
  enrollmentDate: Timestamp;
  /**
   * pending_confirmation, completed
   */
  enrollmentStatus: Generated<string | null>;
  feesAmount: Numeric | null;
  feesCategory: string | null;
  feesPaid: Generated<boolean | null>;
  feesReceiptNo: string | null;
  gradeId: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  schoolId: Int8;
  streamId: Int8 | null;
  studentId: Int8 | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface EntranceExams {
  applicationId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  examDate: Timestamp;
  /**
   * Links to exam definition/subject
   */
  examDefinitionId: Int8 | null;
  /**
   * Chief examiner responsible for the exam
   */
  examinerId: Int8 | null;
  examinerName: string | null;
  examVenue: string | null;
  grade: string | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  /**
   * Staff who marked the exam script
   */
  markerId: Int8 | null;
  markerName: string | null;
  marksObtained: number;
  /**
   * Notes from second marking/moderation
   */
  moderationNotes: string | null;
  percentage: Generated<Numeric | null>;
  remarks: string | null;
  schoolId: Int8;
  /**
   * Links to exam session/batch
   */
  sessionId: Int8 | null;
  /**
   * Staff who supervised/invigilated the exam
   */
  supervisorId: Int8 | null;
  supervisorName: string | null;
  totalMarks: number;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface EventTypes {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ExamConductors {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  examId: Int8;
  id: Generated<Int8>;
  /**
   * Role in exam: lead, invigilator, assistant, supervisor, team member, coordinator
   */
  role: Generated<string | null>;
  staffId: Int8;
}

export interface ExamDefinitions {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  durationMinutes: number | null;
  examCode: string;
  examName: string;
  gradingScale: Generated<string | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  schoolId: Int8;
  subjectArea: string | null;
  totalMarks: Generated<number | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ExamResults {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  examId: Int8;
  gradedBy: Int8 | null;
  gradeLetter: string | null;
  gradePoint: Numeric | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  isFinal: Generated<boolean | null>;
  remarks: string | null;
  schoolId: Int8;
  score: Numeric;
  statusId: Int8 | null;
  studentId: Int8;
  teacherComments: Generated<Json | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Exams {
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  endTime: string;
  examDate: Timestamp;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  maxScore: Numeric;
  schoolId: Int8;
  startTime: string;
  statusId: Int8 | null;
  subjectId: Int8;
  teacherComments: Generated<Json | null>;
  teacherId: Int8 | null;
  termId: Int8;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  /**
   * Weight for grade aggregation (0.1 to 1.0). Used to calculate final grades when combining multiple exam/assessment types.
   */
  weight: Generated<Numeric | null>;
}

export interface ExamSessions {
  academicYear: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  endDate: Timestamp | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  schoolId: Int8;
  sessionCode: string;
  sessionName: string;
  startDate: Timestamp | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ExtensionsHypopgHiddenIndexes {
  amName: string | null;
  indexName: string | null;
  indexrelid: number | null;
  isHypo: boolean | null;
  schemaName: string | null;
  tableName: string | null;
}

export interface ExtensionsHypopgListIndexes {
  amName: string | null;
  indexName: string | null;
  indexrelid: number | null;
  schemaName: string | null;
  tableName: string | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jitDeformCount: Int8 | null;
  jitDeformTime: number | null;
  jitEmissionCount: Int8 | null;
  jitEmissionTime: number | null;
  jitFunctions: Int8 | null;
  jitGenerationTime: number | null;
  jitInliningCount: Int8 | null;
  jitInliningTime: number | null;
  jitOptimizationCount: Int8 | null;
  jitOptimizationTime: number | null;
  localBlkReadTime: number | null;
  localBlksDirtied: Int8 | null;
  localBlksHit: Int8 | null;
  localBlksRead: Int8 | null;
  localBlksWritten: Int8 | null;
  localBlkWriteTime: number | null;
  maxExecTime: number | null;
  maxPlanTime: number | null;
  meanExecTime: number | null;
  meanPlanTime: number | null;
  minExecTime: number | null;
  minmaxStatsSince: Timestamp | null;
  minPlanTime: number | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  sharedBlkReadTime: number | null;
  sharedBlksDirtied: Int8 | null;
  sharedBlksHit: Int8 | null;
  sharedBlksRead: Int8 | null;
  sharedBlksWritten: Int8 | null;
  sharedBlkWriteTime: number | null;
  statsSince: Timestamp | null;
  stddevExecTime: number | null;
  stddevPlanTime: number | null;
  tempBlkReadTime: number | null;
  tempBlksRead: Int8 | null;
  tempBlksWritten: Int8 | null;
  tempBlkWriteTime: number | null;
  toplevel: boolean | null;
  totalExecTime: number | null;
  totalPlanTime: number | null;
  userid: number | null;
  walBytes: Numeric | null;
  walFpi: Int8 | null;
  walRecords: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  statsReset: Timestamp | null;
}

export interface Genders {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface GradeLevels {
  code: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  description: string | null;
  displayOrder: Generated<number | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface GradingConfigurations {
  academicYearId: Int8 | null;
  /**
   * Percentage weight for assessments in final grade (0-100)
   */
  assessmentsWeight: Generated<Numeric | null>;
  /**
   * Percentage weight for assignments in final grade (0-100)
   */
  assignmentsWeight: Generated<Numeric | null>;
  /**
   * Method: weighted_average, total_points, or category_average
   */
  calculationMethod: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  decimalPlaces: Generated<number | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  effectiveEndDate: Timestamp | null;
  effectiveStartDate: Timestamp | null;
  /**
   * Percentage weight for exams in final grade (0-100)
   */
  examsWeight: Generated<Numeric | null>;
  /**
   * JSON array defining grade boundaries, points, and descriptions
   */
  gradingScale: Generated<Json>;
  id: Generated<Int8>;
  includeUngraded: Generated<boolean | null>;
  isActive: Generated<boolean | null>;
  isDefault: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  roundFinalGrade: Generated<boolean | null>;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface GradingScales {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Guardians {
  address: string | null;
  alternatePhone: string | null;
  /**
   * Authorized to pick up student from school
   */
  canPickup: Generated<boolean | null>;
  city: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  district: string | null;
  email: string | null;
  employer: string | null;
  firstName: string;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  /**
   * Authorized emergency contact
   */
  isEmergencyContact: Generated<boolean | null>;
  /**
   * Primary contact guardian
   */
  isPrimary: Generated<boolean | null>;
  lastName: string;
  occupation: string | null;
  phone: string | null;
  relationship: string;
  schoolId: Int8;
  studentId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  userId: Int8 | null;
}

export interface Interviews {
  applicationId: Int8;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  interviewerIds: ArrayType<Int8> | null;
  interviewNotes: string | null;
  interviewOutcome: string | null;
  interviewScore: Numeric | null;
  interviewType: Generated<string | null>;
  isCompleted: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  location: string | null;
  outcomeNotes: string | null;
  scheduledDate: Timestamp;
  scheduledEndTime: Timestamp | null;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface JobApplications {
  appliedAt: Generated<Timestamp | null>;
  coverLetter: string | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  email: string;
  firstName: string;
  id: Generated<Int8>;
  interviewDate: Timestamp | null;
  interviewerId: Int8 | null;
  isDeleted: Generated<boolean | null>;
  jobId: Int8 | null;
  lastName: string;
  notes: string | null;
  phone: string | null;
  resumeUrl: string | null;
  schoolId: Int8;
  status: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Jobs {
  closingDate: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  departmentId: Int8 | null;
  description: string | null;
  employmentType: string | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  location: string | null;
  postedAt: Timestamp | null;
  requirements: string | null;
  responsibilities: string | null;
  salaryCurrency: string | null;
  salaryMax: Numeric | null;
  salaryMin: Numeric | null;
  schoolId: Int8;
  status: Generated<string | null>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface LeaveRequests {
  approvedAt: Timestamp | null;
  approvedBy: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  endDate: Timestamp;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  leaveTypeId: Int8 | null;
  reason: string | null;
  rejectionReason: string | null;
  schoolId: Int8;
  staffId: Int8;
  startDate: Timestamp;
  status: Generated<string | null>;
  totalDays: Numeric | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Leaves {
  appliedAt: Generated<Timestamp | null>;
  approvedAt: Timestamp | null;
  approvedBy: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  documentUrl: string | null;
  endDate: Timestamp;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  isEmergency: Generated<boolean | null>;
  leaveTypeId: Int8;
  reason: string;
  rejectReason: string | null;
  schoolId: Int8;
  startDate: Timestamp;
  status: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  userId: Int8;
}

export interface LeaveTypes {
  category: string | null;
  code: string;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  isPaid: Generated<boolean | null>;
  maxConsecutiveDays: number | null;
  maxDaysPerYear: number | null;
  name: string;
  requiresApproval: Generated<boolean | null>;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface LessonDeliveries {
  actualEndTime: string | null;
  actualStartTime: string | null;
  attendanceCount: Generated<number | null>;
  challengesFaced: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  deliveredAt: Timestamp | null;
  followUpNeeded: Generated<boolean | null>;
  followUpNotes: string | null;
  homeworkAssigned: Generated<Json | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  lessonId: Int8 | null;
  objectivesCovered: boolean | null;
  rescheduledFromId: Int8 | null;
  rescheduledToDate: Timestamp | null;
  resourcesUsed: Generated<Json | null>;
  scheduledDate: Timestamp;
  schoolId: Int8;
  status: Generated<string>;
  teacherNotes: string | null;
  timetableEntryId: Int8 | null;
  totalStudents: Generated<number | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Lessons {
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  endTime: string;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  lessonPlan: Generated<Json | null>;
  resources: Json | null;
  room: string | null;
  scheduledDate: Timestamp;
  schoolId: Int8;
  startTime: string;
  statusId: Int8 | null;
  subjectId: Int8;
  teacherComments: Generated<Json | null>;
  teacherId: Int8;
  termId: Int8 | null;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface PerformanceReviews {
  acknowledgedAt: Timestamp | null;
  areasForImprovement: string | null;
  comments: string | null;
  communication: number | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  goalsAchievement: number | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  overallRating: number | null;
  professionalism: number | null;
  recommendations: string | null;
  reviewDate: Timestamp | null;
  reviewerId: Int8 | null;
  reviewPeriodEnd: Timestamp | null;
  reviewPeriodStart: Timestamp | null;
  schoolId: Int8;
  staffId: Int8;
  status: Generated<string | null>;
  strengths: string | null;
  teamwork: number | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Permissions {
  action: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isDeleted: Generated<boolean>;
  module: string;
  name: string;
  permissionKey: Generated<string | null>;
  resource: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface RealtimeMessages {
  event: string | null;
  extension: string;
  id: Generated<string>;
  insertedAt: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updatedAt: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  insertedAt: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  actionFilter: Generated<string | null>;
  claims: Json;
  claimsRole: Generated<string>;
  createdAt: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  subscriptionId: string;
}

export interface RelationshipTypes {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface ReportCards {
  attendancePercentage: Numeric | null;
  classTeacherId: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  gpa: Numeric | null;
  gradeLetter: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  percentage: Numeric | null;
  schoolId: Int8;
  statusId: Int8 | null;
  studentId: Int8;
  teacherComments: Generated<Json | null>;
  termId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface RolePermissions {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  permissionKey: string;
  roleId: Int8;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Roles {
  code: number;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean>;
  isSystem: Generated<boolean>;
  module: string;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface RoutePermissions {
  action: string;
  createdAt: Generated<Timestamp | null>;
  displayName: string | null;
  displayOrder: Generated<number | null>;
  groupName: string | null;
  icon: Generated<string | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isGlobal: Generated<boolean | null>;
  isMenuItem: Generated<boolean | null>;
  method: string;
  module: string;
  permissionKey: string | null;
  resource: string;
  route: string;
  routeType: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Schools {
  address: string;
  code: string;
  contactEmail: string;
  contactPhone: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  districtId: Int8;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  logoUrl: string | null;
  name: string;
  settings: Json | null;
  timezone: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Staff {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  departmentId: Int8 | null;
  employeeNo: string | null;
  hireDate: Generated<Timestamp | null>;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  roleId: Int8 | null;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  userId: Int8;
}

export interface StaffAttendance {
  clockInTime: Timestamp | null;
  clockOutTime: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  date: Timestamp;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  deviceId: string | null;
  earlyLeaveMinutes: Generated<number | null>;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  lateMinutes: Generated<number | null>;
  notes: string | null;
  schoolId: Int8;
  staffId: Int8;
  status: Generated<string | null>;
  totalHours: Numeric | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface StaffCertifications {
  createdAt: Generated<Timestamp | null>;
  credentialId: string | null;
  credentialUrl: string | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  documentUrl: string | null;
  expiryDate: Timestamp | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  issueDate: Timestamp | null;
  issuer: string | null;
  name: string;
  schoolId: Int8;
  staffId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface StaffContracts {
  contractNumber: string | null;
  contractType: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  departmentId: Int8 | null;
  documentUrl: string | null;
  endDate: Timestamp | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  jobTitle: string | null;
  noticePeriodDays: number | null;
  probationPeriodDays: number | null;
  salary: Numeric | null;
  salaryCurrency: string | null;
  salaryFrequency: Generated<string | null>;
  schoolId: Int8;
  signedAt: Timestamp | null;
  signedBy: Int8 | null;
  staffId: Int8;
  startDate: Timestamp;
  status: Generated<string | null>;
  terms: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface StaffIdAccess {
  accessLevel: Generated<string | null>;
  accessZones: Json | null;
  allowedBuildings: Json | null;
  allowedEntries: Json | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  fingerprintId: string | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  issuedAt: Timestamp | null;
  issuedBy: Int8 | null;
  returnedAt: Timestamp | null;
  rfidCardNumber: string | null;
  schoolId: Int8;
  staffId: Int8;
  staffIdNumber: string | null;
  status: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
  validFrom: Timestamp | null;
  validUntil: Timestamp | null;
}

export interface StaffLeaveQuotas {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  leaveTypeId: Int8 | null;
  remainingDays: Numeric | null;
  schoolId: Int8;
  staffId: Int8;
  totalDays: Numeric;
  updatedAt: Generated<Timestamp | null>;
  usedDays: Generated<Numeric | null>;
  year: number;
}

export interface StaffmgtPromotionHistoryView {
  createdAt: Timestamp | null;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  employeeNo: string | null;
  hireDate: Timestamp | null;
  id: Int8 | null;
  isActive: boolean | null;
  isDeleted: boolean | null;
  newDepartmentId: Int8 | null;
  newDepartmentName: string | null;
  newRoleId: Int8 | null;
  newRoleName: string | null;
  oldDepartmentId: Int8 | null;
  oldDepartmentName: string | null;
  oldRoleId: Int8 | null;
  oldRoleName: string | null;
  promotionDate: Timestamp | null;
  promotionId: Int8 | null;
  remarks: string | null;
  schoolId: Int8 | null;
  staffmgtId: Int8 | null;
  updatedAt: Timestamp | null;
  updatedBy: Int8 | null;
  userId: Int8 | null;
}

export interface StaffmgtPromotions {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  newDepartmentId: Int8 | null;
  newRoleId: Int8 | null;
  oldDepartmentId: Int8 | null;
  oldRoleId: Int8 | null;
  promotionDate: Generated<Timestamp>;
  remarks: string | null;
  schoolId: Int8;
  staffmgtId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface StaffmgtRoles {
  code: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface StaffPayroll {
  bankAccountName: string | null;
  bankAccountNumber: string | null;
  bankAccountType: string | null;
  bankName: string | null;
  bankRoutingNumber: string | null;
  baseSalary: Numeric | null;
  benefitsDeductions: Generated<Numeric | null>;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  lastPaidDate: Timestamp | null;
  netSalary: Numeric | null;
  otherDeductions: Generated<Numeric | null>;
  salaryCurrency: Generated<string | null>;
  salaryFrequency: Generated<string | null>;
  schoolId: Int8;
  staffId: Int8;
  taxDeductions: Generated<Numeric | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface StaffPromotions {
  approvedAt: Timestamp | null;
  approvedBy: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  currentSalary: Numeric | null;
  currentTitle: string | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  effectiveDate: Timestamp | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  newSalary: Numeric | null;
  newTitle: string;
  notes: string | null;
  reason: string | null;
  salaryCurrency: string | null;
  schoolId: Int8;
  staffId: Int8;
  status: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface StaffTransfers {
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isDeleted: Generated<boolean>;
  newDepartmentId: Int8;
  oldDepartmentId: Int8 | null;
  remarks: string | null;
  schoolId: Int8;
  staffId: Int8;
  transferDate: Generated<Timestamp>;
  transferredBy: Int8 | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface Statuses {
  code: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  label: string;
  module: string;
  schoolId: Int8 | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface StorageBuckets {
  allowedMimeTypes: string[] | null;
  avifAutodetection: Generated<boolean | null>;
  createdAt: Generated<Timestamp | null>;
  fileSizeLimit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  ownerId: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updatedAt: Generated<Timestamp | null>;
}

export interface StorageBucketsAnalytics {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  format: Generated<string>;
  id: Generated<string>;
  name: string;
  type: Generated<StorageBuckettype>;
  updatedAt: Generated<Timestamp>;
}

export interface StorageBucketsVectors {
  createdAt: Generated<Timestamp>;
  id: string;
  type: Generated<StorageBuckettype>;
  updatedAt: Generated<Timestamp>;
}

export interface StorageMigrations {
  executedAt: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucketId: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<string>;
  lastAccessedAt: Generated<Timestamp | null>;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  ownerId: string | null;
  pathTokens: Generated<string[] | null>;
  updatedAt: Generated<Timestamp | null>;
  userMetadata: Json | null;
  version: string | null;
}

export interface StorageS3MultipartUploads {
  bucketId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  inProgressSize: Generated<Int8>;
  key: string;
  metadata: Json | null;
  ownerId: string | null;
  uploadSignature: string;
  userMetadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucketId: string;
  createdAt: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  ownerId: string | null;
  partNumber: number;
  size: Generated<Int8>;
  uploadId: string;
  version: string;
}

export interface StorageVectorIndexes {
  bucketId: string;
  createdAt: Generated<Timestamp>;
  dataType: string;
  dimension: number;
  distanceMetric: string;
  id: Generated<string>;
  metadataConfiguration: Json | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Streams {
  code: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface StudentConductLogs {
  category: string;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<Int8>;
  incidentDate: Generated<Timestamp | null>;
  isDeleted: Generated<boolean | null>;
  isVerified: Generated<boolean | null>;
  loggedBy: Int8;
  points: number;
  schoolId: Int8;
  studentId: Int8;
  updatedAt: Generated<Timestamp | null>;
}

export interface StudentHouses {
  colorCode: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  houseMasterId: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  motto: string | null;
  name: string;
  schoolId: Int8;
}

export interface StudentIdRegistry {
  cardUuid: string | null;
  createdAt: Generated<Timestamp | null>;
  expiryDate: Timestamp | null;
  id: Generated<Int8>;
  issueDate: Generated<Timestamp | null>;
  lastScannedAt: Timestamp | null;
  schoolId: Int8;
  status: Generated<string | null>;
  studentId: Int8;
}

export interface StudentPromotions {
  academicYearId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  fromClassId: Int8;
  fromGradeLevelId: Int8;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  promotionDate: Generated<Timestamp | null>;
  remarks: string | null;
  schoolId: Int8;
  status: Generated<string | null>;
  studentId: Int8;
  toClassId: Int8;
  toGradeLevelId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface StudentRelationships {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  notes: string | null;
  relatedStudentId: Int8 | null;
  /**
   * Type of relationship: sibling, cousin, etc.
   */
  relationshipType: string;
  schoolId: Int8;
  studentId: Int8;
}

export interface Students {
  address: string | null;
  admissionDate: Timestamp | null;
  admissionNo: Int8;
  admissionStatusId: Int8 | null;
  allergies: string | null;
  applicationDate: Generated<Timestamp | null>;
  birthCertificateNo: string | null;
  bloodType: string | null;
  city: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  /**
   * Current class/section
   */
  currentClassId: Int8 | null;
  /**
   * Current grade level
   */
  currentGradeId: Int8 | null;
  currentStream: string | null;
  dateOfBirth: Timestamp;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  district: string | null;
  email: string | null;
  /**
   * Current academic status: active, graduated, transferred, withdrawn, suspended, on_leave
   */
  enrollmentStatus: Generated<string | null>;
  firstName: string;
  gender: string | null;
  guardianContact: string | null;
  guardianName: string | null;
  houseId: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  lastName: string;
  medicalConditions: string | null;
  middleName: string | null;
  nationality: Generated<string | null>;
  phone: string | null;
  photoUrl: string | null;
  previousSchool: string | null;
  schoolId: Int8;
  specialNeeds: string | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  /**
   * Links to users table for authentication
   */
  userId: Int8 | null;
}

export interface StudentStatusHistory {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  documentUrl: string | null;
  effectiveDate: Timestamp;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  notes: string | null;
  previousStatus: string | null;
  processedBy: Int8 | null;
  reason: string | null;
  schoolId: Int8;
  status: string;
  studentId: Int8;
}

export interface StudentWellbeingPulse {
  createdAt: Generated<Timestamp | null>;
  energyLevel: number | null;
  id: Generated<Int8>;
  loggedBy: Int8 | null;
  notes: string | null;
  pulseDate: Generated<Timestamp | null>;
  schoolId: Int8;
  sentimentScore: number | null;
  studentId: Int8;
}

export interface Subjects {
  code: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  curriculumId: Int8 | null;
  description: string | null;
  gradeLevelId: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isCore: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  subjectArea: string | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface SystemRolerouteAccessView {
  displayName: string | null;
  method: string | null;
  permissionKey: string | null;
  roleId: number | null;
  roleName: string | null;
  route: string | null;
}

export interface Terms {
  academicYearId: Int8;
  code: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  endDate: Timestamp;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  startDate: Timestamp;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface TimetableEntries {
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  dayOfWeek: string;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  endTime: string;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  room: string | null;
  schoolId: Int8;
  startTime: string;
  subjectId: Int8 | null;
  teacherId: Int8 | null;
  timetableId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface Timetables {
  classId: Int8;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  schoolId: Int8;
  termId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
}

export interface TrainingCourses {
  category: string | null;
  certificateUrl: string | null;
  cost: Numeric | null;
  createdAt: Generated<Timestamp | null>;
  currency: string | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  description: string | null;
  durationHours: Numeric | null;
  endDate: Timestamp;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  isOnline: Generated<boolean | null>;
  location: string | null;
  maxParticipants: number | null;
  provider: string | null;
  schoolId: Int8;
  startDate: Timestamp;
  status: Generated<string | null>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface TrainingEnrollments {
  certificateUrl: string | null;
  completedAt: Timestamp | null;
  courseId: Int8 | null;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  enrolledAt: Generated<Timestamp | null>;
  feedback: string | null;
  grade: string | null;
  id: Generated<Int8>;
  isDeleted: Generated<boolean | null>;
  schoolId: Int8;
  staffId: Int8;
  status: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserAuthMap {
  authUid: string;
  userId: Int8;
}

export interface UserPermissions {
  action: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean | null>;
  isAllowed: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  module: string;
  permissionId: Int8 | null;
  resource: string;
  revokedAt: Timestamp | null;
  revokedBy: Int8 | null;
  schoolId: Int8;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: Int8 | null;
  userId: Int8;
}

export interface UserRoles {
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isDeleted: Generated<boolean>;
  roleId: Int8;
  schoolId: Int8;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
  userId: Int8;
}

export interface Users {
  authUid: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  dateOfBirth: Timestamp | null;
  deletedAt: Timestamp | null;
  deletedBy: Int8 | null;
  email: string | null;
  firstName: string;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isDeleted: Generated<boolean>;
  lastLogin: Timestamp | null;
  lastName: string;
  nationality: Generated<string | null>;
  password: string;
  phone: string | null;
  roleId: Int8 | null;
  schoolId: Int8;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
  username: string;
}

export interface VaultDecryptedSecrets {
  createdAt: Timestamp | null;
  decryptedSecret: string | null;
  description: string | null;
  id: string | null;
  keyId: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updatedAt: Timestamp | null;
}

export interface VaultSecrets {
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  keyId: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updatedAt: Generated<Timestamp>;
}

export interface VHouseLeaderboard {
  colorCode: string | null;
  houseName: string | null;
  memberCount: Int8 | null;
  schoolId: Int8 | null;
  totalPoints: Int8 | null;
}

export interface VLessonDeliveriesDetail {
  actualEndTime: string | null;
  actualStartTime: string | null;
  attendanceCount: number | null;
  challengesFaced: string | null;
  classCode: string | null;
  className: string | null;
  createdAt: Timestamp | null;
  deliveredAt: Timestamp | null;
  deliveryId: Int8 | null;
  followUpNeeded: boolean | null;
  followUpNotes: string | null;
  homeworkAssigned: Json | null;
  lessonEndTime: string | null;
  lessonId: Int8 | null;
  lessonStartTime: string | null;
  lessonTemplateEnd: string | null;
  lessonTemplateStart: string | null;
  objectivesCovered: boolean | null;
  originalScheduledDate: Timestamp | null;
  originalStatus: string | null;
  rescheduledFromId: Int8 | null;
  rescheduledScheduledDate: Timestamp | null;
  rescheduledStatus: string | null;
  rescheduledToDate: Timestamp | null;
  resourcesUsed: Json | null;
  scheduledDate: Timestamp | null;
  status: string | null;
  subjectCode: string | null;
  subjectName: string | null;
  teacherName: string | null;
  teacherNotes: string | null;
  timetableEntryId: Int8 | null;
  totalStudents: number | null;
  updatedAt: Timestamp | null;
}

export interface VTodaysLessonDeliveries {
  attendanceCount: number | null;
  challengesFaced: string | null;
  classCode: string | null;
  className: string | null;
  deliveryId: Int8 | null;
  endTime: string | null;
  followUpNeeded: boolean | null;
  followUpNotes: string | null;
  homeworkAssigned: Json | null;
  lessonId: Int8 | null;
  objectivesCovered: boolean | null;
  resourcesUsed: Json | null;
  scheduledDate: Timestamp | null;
  startTime: string | null;
  status: string | null;
  subjectCode: string | null;
  subjectName: string | null;
  teacherName: string | null;
  teacherNotes: string | null;
  timetableEntryId: Int8 | null;
  totalStudents: number | null;
}

export interface DB {
  academicsAssignmentSubmissionsView: AcademicsAssignmentSubmissionsView;
  academicsClassscheduleView: AcademicsClassscheduleView;
  academicYears: AcademicYears;
  admissionStatuses: AdmissionStatuses;
  applicants: Applicants;
  applicationDecisions: ApplicationDecisions;
  applicationDocuments: ApplicationDocuments;
  applications: Applications;
  applicationTypes: ApplicationTypes;
  assessmentConductors: AssessmentConductors;
  assessmentResults: AssessmentResults;
  assessments: Assessments;
  assessmentTypes: AssessmentTypes;
  assetAssignments: AssetAssignments;
  assetMaintenanceLogs: AssetMaintenanceLogs;
  assets: Assets;
  assetTypes: AssetTypes;
  assignments: Assignments;
  assignmentSubmissions: AssignmentSubmissions;
  attendancePolicies: AttendancePolicies;
  attendanceRecords: AttendanceRecords;
  attendanceSessions: AttendanceSessions;
  attendanceStatus: AttendanceStatus;
  attendanceSummary: AttendanceSummary;
  auditlogs: Auditlogs;
  auditlogsReport: AuditlogsReport;
  auditrouteReport: AuditrouteReport;
  "auth.auditLogEntries": AuthAuditLogEntries;
  "auth.customOauthProviders": AuthCustomOauthProviders;
  "auth.flowState": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfaAmrClaims": AuthMfaAmrClaims;
  "auth.mfaChallenges": AuthMfaChallenges;
  "auth.mfaFactors": AuthMfaFactors;
  "auth.oauthAuthorizations": AuthOauthAuthorizations;
  "auth.oauthClients": AuthOauthClients;
  "auth.oauthClientStates": AuthOauthClientStates;
  "auth.oauthConsents": AuthOauthConsents;
  "auth.oneTimeTokens": AuthOneTimeTokens;
  "auth.refreshTokens": AuthRefreshTokens;
  "auth.samlProviders": AuthSamlProviders;
  "auth.samlRelayStates": AuthSamlRelayStates;
  "auth.schemaMigrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.ssoDomains": AuthSsoDomains;
  "auth.ssoProviders": AuthSsoProviders;
  "auth.users": AuthUsers;
  "auth.webauthnChallenges": AuthWebauthnChallenges;
  "auth.webauthnCredentials": AuthWebauthnCredentials;
  campusAccessLogs: CampusAccessLogs;
  classAttendance: ClassAttendance;
  classes: Classes;
  classStudents: ClassStudents;
  classTeachers: ClassTeachers;
  contactTypes: ContactTypes;
  countries: Countries;
  curricula: Curricula;
  departments: Departments;
  disciplinaryIncidents: DisciplinaryIncidents;
  districts: Districts;
  documentTypes: DocumentTypes;
  educationLevels: EducationLevels;
  employmentTypes: EmploymentTypes;
  enquirerCategories: EnquirerCategories;
  enquiries: Enquiries;
  enquiryCategories: EnquiryCategories;
  enquiryNotes: EnquiryNotes;
  enquirySources: EnquirySources;
  enrollments: Enrollments;
  entranceExams: EntranceExams;
  eventTypes: EventTypes;
  examConductors: ExamConductors;
  examDefinitions: ExamDefinitions;
  examResults: ExamResults;
  exams: Exams;
  examSessions: ExamSessions;
  "extensions.hypopgHiddenIndexes": ExtensionsHypopgHiddenIndexes;
  "extensions.hypopgListIndexes": ExtensionsHypopgListIndexes;
  "extensions.pgStatStatements": ExtensionsPgStatStatements;
  "extensions.pgStatStatementsInfo": ExtensionsPgStatStatementsInfo;
  genders: Genders;
  gradeLevels: GradeLevels;
  gradingConfigurations: GradingConfigurations;
  gradingScales: GradingScales;
  guardians: Guardians;
  interviews: Interviews;
  jobApplications: JobApplications;
  jobs: Jobs;
  leaveRequests: LeaveRequests;
  leaves: Leaves;
  leaveTypes: LeaveTypes;
  lessonDeliveries: LessonDeliveries;
  lessons: Lessons;
  performanceReviews: PerformanceReviews;
  permissions: Permissions;
  "realtime.messages": RealtimeMessages;
  "realtime.schemaMigrations": RealtimeSchemaMigrations;
  "realtime.subscription": RealtimeSubscription;
  relationshipTypes: RelationshipTypes;
  reportCards: ReportCards;
  rolePermissions: RolePermissions;
  roles: Roles;
  routePermissions: RoutePermissions;
  schools: Schools;
  staff: Staff;
  staffAttendance: StaffAttendance;
  staffCertifications: StaffCertifications;
  staffContracts: StaffContracts;
  staffIdAccess: StaffIdAccess;
  staffLeaveQuotas: StaffLeaveQuotas;
  staffmgtPromotionHistoryView: StaffmgtPromotionHistoryView;
  staffmgtPromotions: StaffmgtPromotions;
  staffmgtRoles: StaffmgtRoles;
  staffPayroll: StaffPayroll;
  staffPromotions: StaffPromotions;
  staffTransfers: StaffTransfers;
  statuses: Statuses;
  "storage.buckets": StorageBuckets;
  "storage.bucketsAnalytics": StorageBucketsAnalytics;
  "storage.bucketsVectors": StorageBucketsVectors;
  "storage.migrations": StorageMigrations;
  "storage.objects": StorageObjects;
  "storage.s3MultipartUploads": StorageS3MultipartUploads;
  "storage.s3MultipartUploadsParts": StorageS3MultipartUploadsParts;
  "storage.vectorIndexes": StorageVectorIndexes;
  streams: Streams;
  studentConductLogs: StudentConductLogs;
  studentHouses: StudentHouses;
  studentIdRegistry: StudentIdRegistry;
  studentPromotions: StudentPromotions;
  studentRelationships: StudentRelationships;
  students: Students;
  studentStatusHistory: StudentStatusHistory;
  studentWellbeingPulse: StudentWellbeingPulse;
  subjects: Subjects;
  systemRolerouteAccessView: SystemRolerouteAccessView;
  terms: Terms;
  timetableEntries: TimetableEntries;
  timetables: Timetables;
  trainingCourses: TrainingCourses;
  trainingEnrollments: TrainingEnrollments;
  userAuthMap: UserAuthMap;
  userPermissions: UserPermissions;
  userRoles: UserRoles;
  users: Users;
  "vault.decryptedSecrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
  vHouseLeaderboard: VHouseLeaderboard;
  vLessonDeliveriesDetail: VLessonDeliveriesDetail;
  vTodaysLessonDeliveries: VTodaysLessonDeliveries;
}
